@startuml
node "Клиентская сторона" {
  [Веб-приложение MPA (Node.js)]
}

node "Серверная часть" {
  [Модуль пользователя]
  [Модуль мастер-классов]
  [Модуль GIS]
}

database "База данных PostgreSQL" {
  [Данные пользователей]
  [Данные мастер-классов]
}

node "Сервисы" {
  [Сервис платежей]
  [Яндекс-Геокодер]
  [OpenStreetMap]
}

[Веб-приложение MPA (Node.js)] --> [Серверная часть] : HTTP/HTTPS

[Модуль пользователя] --> [Данные пользователей] : Чтение/Запись
[Модуль мастер-классов] --> [Данные мастер-классов] : Чтение/Запись
[Модуль GIS] --> [Данные мастер-классов] : Чтение/Запись

[Серверная часть] --> [Сервис платежей] : API запросы
[Модуль GIS] --> [Яндекс-Геокодер] : API запросы
[Модуль GIS] --> [OpenStreetMap] : API запросы

@enduml
