# Generated by Django 5.0 on 2024-04-29 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, max_length=1000, null=True, upload_to='organizer_logos/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('location_name', models.TextField(verbose_name='Название места')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('start_time', models.TextField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('registration_deadline', models.TextField(verbose_name='Крайний срок регистрации')),
                ('categories', models.ManyToManyField(to='masterclasses.category', verbose_name='Категории')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_masterclasses', to='masterclasses.organizer', verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Мастер-класс',
                'verbose_name_plural': 'Мастер-классы',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('masterclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='masterclasses.masterclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participating_masterclasses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('title', models.TextField()),
                ('profile_image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='speaker_profiles/')),
                ('masterclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masterclass_speakers', to='masterclasses.masterclass')),
            ],
        ),
        migrations.AddField(
            model_name='masterclass',
            name='speakers',
            field=models.ManyToManyField(related_name='masterclasses', to='masterclasses.speaker', verbose_name='Спикеры'),
        ),
    ]
