# Generated by Django 5.0 on 2024-06-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterclass',
            name='image',
        ),
        migrations.AddField(
            model_name='masterclass',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
